# Generated by Django 4.2.7 on 2024-08-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0013_class_dore'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendedSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='پیامک', max_length=100)),
                ('to_number', models.CharField(max_length=11, verbose_name='شماره ارسالی')),
                ('send_type', models.CharField(choices=[('shared', 'خدماتی'), ('simple', 'ساده')], default='shared', max_length=15, verbose_name='نوع ارسال')),
                ('pattern_id', models.IntegerField(blank=True, null=True, verbose_name='کد پترن خدماتی')),
                ('last_status', models.CharField(choices=[('0', 'ارسال ناموفق(سایت)'), ('1', 'ارسال ناموفق(سامانه)'), ('2', 'ارسال موفق'), ('3', 'رسیده به مخاطب'), ('4', 'نرسیده به مخاطب'), ('5', 'ارسال شده(نتیجه نامشخص)')], default='5', max_length=32, verbose_name='آخرین وضعیت ارسال')),
                ('params', models.CharField(blank=True, max_length=255, null=True)),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student', verbose_name='متربی')),
            ],
            options={
                'verbose_name': 'پیامک ارسالی',
                'verbose_name_plural': 'پیامک های ارسالی',
            },
        ),
    ]
