# Generated by Django 4.2.7 on 2024-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedsms',
            name='recId',
            field=models.IntegerField(default=1, verbose_name='شناسه ارسالی پیامک'),
            preserve_default=False,
        ),
    ]
