# Generated by Django 4.2.7 on 2024-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management', '0003_alter_sendedsms_last_status_alter_sendedsms_recid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedsms',
            name='recId',
            field=models.CharField(default='-1', max_length=64, verbose_name='شناسه ارسالی پیامک'),
        ),
    ]
