# Generated by Django 4.2.7 on 2025-09-26 09:32

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0012_alter_tuition_is_paid'),
        ('education_management', '0021_selectedlesson_manager_confirm'),
        ('sms_management', '0004_alter_sendedsms_recid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedsms',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم'),
        ),
        migrations.AddField(
            model_name='sendedsms',
            name='tuition_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionterm', verbose_name='شهریه ترم'),
        ),
        migrations.AlterField(
            model_name='sendedsms',
            name='send_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
    ]
