# Generated by Django 4.2.7 on 2023-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='سال')),
                ('mterm', models.CharField(choices=[('T', 'تابستان'), ('M', 'مهر'), ('B', 'بهمن')], default='T', max_length=20, verbose_name='سه ماهه ترم')),
                ('is_active', models.BooleanField(default=False, verbose_name='ترم فعال')),
            ],
        ),
    ]
