# Generated by Django 4.2.7 on 2024-01-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_student_clas'),
        ('education_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='مورد انضباطی')),
            ],
            options={
                'verbose_name': 'مورد\u200c انضباطی',
                'verbose_name_plural': 'موارد انضباطی',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام درس')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات درس')),
                ('ratio', models.IntegerField(default=1, max_length=2, verbose_name='ضریب درس')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نوع درس')),
            ],
            options={
                'verbose_name': 'نوع درس',
                'verbose_name_plural': 'انواع درس',
            },
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'نیم\u200cسال تحصیلی', 'verbose_name_plural': 'نیم\u200cسال\u200cهای\u200cتحصیلی'},
        ),
        migrations.AlterField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نیم\u200cسال فعال'),
        ),
        migrations.AlterField(
            model_name='term',
            name='mterm',
            field=models.CharField(choices=[('T', 'تابستان'), ('M', 'پاییز'), ('B', 'زمستان-بهار')], default='T', max_length=20, verbose_name='نیم\u200cسال'),
        ),
        migrations.CreateModel(
            name='SelectedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[(1, 'عالی'), (2, 'بسیار خوب'), (3, 'خوب'), (4, 'متوسط'), (5, 'ضعیف'), (6, 'بسیارضعیف'), (7, 'غایب'), (8, 'ثبت نشده')], default=8, max_length=2, null=True, verbose_name='نمره\u200c')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.lesson', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student', verbose_name='متربی')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم\u200cتحصیلی')),
            ],
            options={
                'verbose_name': 'درس گرفته\u200cشده',
                'verbose_name_plural': 'درس\u200cهای گرفته\u200cشده',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education_management.lessontype', verbose_name='نوع درس'),
        ),
        migrations.CreateModel(
            name='DisciplineGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='زمان ثبت')),
                ('grade', models.IntegerField(max_length=2, verbose_name='نمره')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.discipline', verbose_name='مورد انضباطی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student', verbose_name='متربی')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم\u200cتحصیلی')),
            ],
            options={
                'verbose_name': 'نمره انضباطی',
                'verbose_name_plural': 'نمرات انضباطی',
            },
        ),
    ]
