# Generated by Django 4.2.7 on 2024-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0002_discipline_lesson_lessontype_alter_term_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinegrade',
            name='grade',
            field=models.IntegerField(verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ratio',
            field=models.IntegerField(default=1, verbose_name='ضریب درس'),
        ),
        migrations.AlterField(
            model_name='selectedlesson',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'عالی'), ('2', 'بسیارخوب'), ('3', 'خوب'), ('4', 'متوسط'), ('5', 'ضعیف'), ('6', 'بسیارضعیف'), ('7', 'غایب'), ('8', 'ثبت\u200cنشده')], default='8', max_length=10, null=True, verbose_name='نمره\u200c'),
        ),
    ]
