# Generated by Django 4.2.7 on 2024-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0003_alter_disciplinegrade_grade_alter_lesson_ratio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='selectedlesson',
            constraint=models.UniqueConstraint(fields=('student', 'lesson', 'term'), name='unique_student_term_lesson'),
        ),
    ]
