# Generated by Django 4.2.7 on 2024-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0004_selectedlesson_unique_student_term_lesson'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year', 'mterm'), name='unique_term'),
        ),
    ]
