# Generated by Django 4.2.7 on 2024-01-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_student_register_date'),
        ('education_management', '0005_term_unique_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.class', verbose_name='گروه')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.lesson', verbose_name='درس')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم\u200cتحصیلی')),
            ],
            options={
                'verbose_name': 'کنترل انتخاب واحد گروه ها ',
            },
        ),
        migrations.AddConstraint(
            model_name='controlselection',
            constraint=models.UniqueConstraint(fields=('clas', 'lesson', 'term'), name='unique_clas_term_lesson'),
        ),
    ]
