# Generated by Django 4.2.7 on 2024-01-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0006_controlselection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlselection',
            options={'verbose_name': 'کنترل انتخاب واحد گروه', 'verbose_name_plural': 'کنترل انتخاب واحد گروه ها'},
        ),
    ]
