# Generated by Django 4.2.7 on 2024-01-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0009_selectedlesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedlesson',
            name='description',
            field=models.CharField(blank=True, default='توضیحات', max_length=255, null=True, verbose_name='توضیحات'),
        ),
    ]
