# Generated by Django 4.2.7 on 2024-03-02 12:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0011_alter_disciplinegrade_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinegrade',
            name='created',
            field=django_jalali.db.models.jDateField(verbose_name='زمان ثبت'),
        ),
    ]
