# Generated by Django 4.2.7 on 2024-03-02 13:12

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_class_dore'),
        ('education_management', '0012_alter_disciplinegrade_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='برگزاری گروه', max_length=60)),
                ('report_type', models.CharField(blank=True, choices=[('r', 'روز گروه'), ('f', 'فوق برنامه'), ('o', 'اردو'), ('j', 'جلسه والدین'), ('t', 'تشکل خانواده ایمانی')], default='n', max_length=10, null=True, verbose_name='نمره\u200c')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ گزارش')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.class', verbose_name='گروه')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم\u200cتحصیلی')),
            ],
            options={
                'verbose_name': 'گزارش روزانه گروه',
                'verbose_name_plural': 'گزارش های روزانه گروه ها',
            },
        ),
        migrations.AddConstraint(
            model_name='groupreport',
            constraint=models.UniqueConstraint(fields=('clas', 'term', 'date', 'report_type'), name='unique_clas_term_date_report_type'),
        ),
    ]
