# Generated by Django 4.2.7 on 2024-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0014_reporttypes_alter_groupreport_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreport',
            name='report_type',
            field=models.CharField(choices=[('r', 'روز گروه'), ('f', 'فوق برنامه'), ('o', 'اردو'), ('j', 'جلسه والدین'), ('t', 'تشکل خانواده ایمانی')], default='r', max_length=20, verbose_name='نوع گزارش'),
        ),
    ]
