# Generated by Django 4.2.7 on 2024-03-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0015_alter_groupreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.reporttypes', verbose_name='نوع گزارش'),
        ),
    ]
