# Generated by Django 4.2.7 on 2024-03-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0016_alter_groupreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinegrade',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_management.groupreport', verbose_name='گزارش گروه'),
        ),
        migrations.AlterField(
            model_name='groupreport',
            name='report_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education_management.reporttypes', verbose_name='نوع گزارش'),
        ),
    ]
