# Generated by Django 4.2.7 on 2025-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0020_remove_reporttypes_grade_reporttypes_grade1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlesson',
            name='manager_confirm',
            field=models.BooleanField(default=False, verbose_name='تاییدیه مدیریت'),
        ),
    ]
