# Generated by Django 4.2.7 on 2025-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_management', '0021_selectedlesson_manager_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinegrade',
            name='is_cal_in_average',
            field=models.BooleanField(default=True, verbose_name='محاسبه در میانگین نمرات'),
        ),
    ]
