# Generated by Django 4.2.7 on 2024-08-22 07:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_management', '0020_remove_reporttypes_grade_reporttypes_grade1_and_more'),
        ('members', '0013_class_dore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='شهریه ترم ... دوره ...', max_length=100)),
                ('price', models.BigIntegerField(default=0, verbose_name='مبلغ شهریه ترم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('groups', models.ManyToManyField(to='members.class', verbose_name='گروه ها')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'شهریه ترم',
                'verbose_name_plural': 'شهریه ترم ها',
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='')),
                ('debt_amount', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='میزان بدهی')),
                ('pay_day_1', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='موعد پرداخت اول')),
                ('pay_day_2', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='موعد پرداخت دوم')),
                ('pay_day_3', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='موعد پرداخت سوم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student', verbose_name='متربی')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم')),
                ('tuition_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionterm', verbose_name='شهریه مرجع')),
            ],
            options={
                'verbose_name': 'شهریه متربی',
                'verbose_name_plural': 'شهریه های متربی ها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ پرداخت')),
                ('pay_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('pay_type', models.CharField(choices=[('1', 'نقدی'), ('2', 'کارت به کارت'), ('3', 'چک'), ('4', 'تخفیف'), ('5', 'سایر')], default='2', max_length=20, verbose_name='نوع پرداخت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student', verbose_name='متربی')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_management.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
