# Generated by Django 4.2.7 on 2024-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tuition',
            constraint=models.UniqueConstraint(fields=('student', 'term'), name='unique_tuition'),
        ),
    ]
