# Generated by Django 4.2.7 on 2024-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_tuition_unique_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionterm',
            name='title',
            field=models.CharField(default='دوره ...', max_length=20, verbose_name='عنوان(دوره)'),
        ),
    ]
