# Generated by Django 4.2.7 on 2024-08-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_class_dore'),
        ('tuition', '0003_alter_tuitionterm_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionterm',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='members.class', verbose_name='گروه ها'),
        ),
    ]
