# Generated by Django 4.2.7 on 2024-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_alter_tuitionterm_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
    ]
