# Generated by Django 4.2.7 on 2024-08-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_payment_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='pay_day_1',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='pay_day_2',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='pay_day_3',
        ),
    ]
