# Generated by Django 4.2.7 on 2024-08-26 10:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_remove_tuition_pay_day_1_remove_tuition_pay_day_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', django_jalali.db.models.jDateField(verbose_name='تاریخ وعده')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ قابل پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuition', verbose_name='شهریه')),
            ],
            options={
                'verbose_name': 'وعده پرداخت',
                'verbose_name_plural': 'وعده های پرداخت',
            },
        ),
    ]
