# Generated by Django 4.2.7 on 2024-08-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management', '0003_alter_sendedsms_last_status_alter_sendedsms_recid'),
        ('tuition', '0008_payday_is_send_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='payday',
            name='sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sms_management.sendedsms', verbose_name='پیامک ارسالی'),
        ),
    ]
