# Generated by Django 4.2.7 on 2024-09-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_alter_tuition_debt_amount_alter_tuitionterm_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='debt_amount',
        ),
    ]
