# Generated by Django 4.2.7 on 2024-09-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0011_remove_tuition_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت تسویه ترم'),
        ),
    ]
