# Generated by Django 4.2.7 on 2025-12-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0012_alter_tuition_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='بدهی/بستانکاری'),
        ),
    ]
