# Generated by Django 4.2.7 on 2025-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0013_payment_is_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='بدهی'),
        ),
    ]
