# Generated by Django 4.2.7 on 2023-12-23 14:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_class_experience_studyfield_member_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'تخصص ها'},
        ),
        migrations.AlterModelOptions(
            name='studyfield',
            options={'verbose_name': 'رشته تحصیلی', 'verbose_name_plural': 'رشته های تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'سرگروه', 'verbose_name_plural': 'سرگروه ها'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان تخصص'),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان رشته'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='clss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.class', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, choices=[('DA', 'متوسطه'), ('KD', 'کاردانی'), ('KA', 'کارشناسی'), ('KAA', 'کارشناسی ارشد'), ('DC', 'دکتری'), ('HZ', 'حوزوی'), ('OT', 'سایر')], default='OT', max_length=100, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experiences',
            field=models.ManyToManyField(blank=True, null=True, to='members.experience', verbose_name='تخصص ها'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='study_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.studyfield', verbose_name='رشته تحصیلی'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('father_name', models.CharField(max_length=30, verbose_name='نام پدر')),
                ('mather_name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی مادر')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.class')),
            ],
            options={
                'verbose_name': 'متربی',
                'verbose_name_plural': 'متربیان',
            },
            bases=('members.member',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
