# Generated by Django 4.2.7 on 2024-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_student_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(default='نامشخص', max_length=50, verbose_name='نام مدرسه '),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=30, verbose_name='نام پدر '),
        ),
    ]
