# Generated by Django 4.2.7 on 2024-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_managers_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(default='نامشخص', max_length=11, verbose_name='شماره موبایل پدر'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_phone',
            field=models.CharField(default='نامشخص', max_length=11, verbose_name='تلفن منزل'),
        ),
        migrations.AddField(
            model_name='student',
            name='mather_phone',
            field=models.CharField(default='نامشخص', max_length=11, verbose_name='شماره موبایل مادر'),
        ),
    ]
