# Generated by Django 4.2.7 on 2024-01-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_student_father_phone_student_home_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل پدر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن منزل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mather_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل مادر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مدرسه '),
        ),
    ]
