# Generated by Django 4.2.7 on 2024-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_student_father_phone_alter_student_home_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'این کد ملی قبلا ثبت شده است .'}, max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
