# Generated by Django 4.2.7 on 2024-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_student_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='dore',
            field=models.CharField(default='0', max_length=2, verbose_name='دوره'),
        ),
    ]
