# Generated by Django 4.2.7 on 2024-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_class_dore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_balance',
            field=models.BigIntegerField(default=0, verbose_name='مانده حساب کل'),
        ),
    ]
