# Generated by Django 4.2.7 on 2025-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_student_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('teacher', 'سرگروه'), ('student', 'متربی')], default='student', max_length=16, verbose_name='نقش کاربر'),
        ),
    ]
